name: "demo_2026"

version: "1.0.0+1"

dependencies:
  # Версии должны быть указаны точно, без диапазонов
  bloc: "9.0.0"
  cupertino_icons: "1.0.8"
  dio: "5.8.0+1"
  flutter:
    sdk: "flutter"
  flutter_bloc: "9.1.0"
  flutter_markdown: "0.7.7"
  flutter_secure_storage: "9.2.4"
  flutter_test:
    sdk: "flutter"
  fluttertoast: "8.2.12"
  freezed_annotation: "3.0.0"
  get_it: "8.0.2"
  go_router: "14.8.1"
  intl: "0.20.2"
  json_annotation: "4.9.0"
  rxdart: "0.28.0"
  shared_preferences: "2.5.3"

dev_dependencies:
  # Версии должны быть указаны точно, без диапазонов
  build_runner: "2.4.15"
  dependency_validator: "5.0.2"
  freezed: "3.0.6"
  ignorium: ">=0.3.2"
  intl_utils: "2.8.10"
  json_serializable: "6.9.5"
  lintorium: ^308.0.0
  mocktail: "1.0.4"
  test: "1.25.15"

flutter_intl:
  enabled: true
  main_locale: ru

flutter:
  generate: false
  uses-material-design: true

environment:
  # Версии должны быть указаны точно, без диапазонов
  sdk: "3.8.1"
  flutter: "3.32.4"

publish_to: "none"